### ISSUE TITLE
Add Basic Website UI to Repository

### ISSUE THREAD

**Issue by AkshayNagamalla** [AkshayNagamalla/codeOptimisationGenAI#2]
The initial version of the basic website UI has been created and is ready to be added to the main repository. Please ensure that all relevant files and components are properly structured and documented before pushing.

Tasks:

 1. Review the existing UI code to ensure it meets project standards.
 2. Confirm that all necessary assets (images, stylesheets, scripts) are included.
 3. Test the UI locally to verify it’s working as expected.
 4. Push the code to the repository in the appropriate folder structure.
Notes:
Tag this commit as "Initial UI push" for easy identification.

**Comment by Sharvani-30** [comment]
I am  working on it.

**Comment by Srinidhi-Chodavarapu** [comment]
Working on it.
